export enum SupportedPlatform{
    WINDOWS,
    MACOS,
    LINUX
}

export global ApplicationState {
    // Application Metadata
    in-out property <string> version: "0.0.0";
    in-out property <string> build: "2026.5.17.123456";
    in-out property <SupportedPlatform> platform: SupportedPlatform.WINDOWS;

    // Window State
    in-out property <length> window-width: 1280px;
    in-out property <length> window-height: 720px;

    // Callbacks
    callback open-url(string);
}
