export global Icons {
    out property <image> plus: @image-url("../../../res/icons/lucide--plus.svg");
    out property <image> upload: @image-url("../../../res/icons/lucide--upload.svg");
    out property <image> magnify: @image-url("../../../res/icons/lucide--search.svg");
    out property <image> key: @image-url("../../../res/icons/lucide--key.svg");
    out property <image> chevron: @image-url("../../../res/icons/lucide--chevron-down.svg");
    out property <image> lock: @image-url("../../../res/icons/lucide--lock.svg");
    out property <image> network: @image-url("../../../res/icons/lucide--network.svg");
}
