import { Theme } from "themes/theme.slint";
import { Button } from "components/Button.slint";
import { Layout } from "themes/layout.slint";
import { VerticalBox } from "std-widgets.slint";
import {
    ConnectionsPage,
    ConnectionsPageEvents,
} from "pages/connections.slint";
import { Titlebar, WindowControls } from "components/Titlebar.slint";
export {WindowControls, ConnectionsPageEvents}
export component MainWindow inherits Window {
    // Window Properties
    title: "quay sftp";
    icon: @image-url("../../../res/icons/icon.png");
    no-frame: true;
    resize-border-width: 5px;

    // Window Sizing
    preferred-width: 1280px;
    preferred-height: 720px;
    min-width: 800px;
    min-height: 400px;

    // Theming
    background: Theme.palette.surface.base;
    default-font-family: Layout.font.sans;
    default-font-size: Layout.text.base;
    default-font-weight: Layout.weight.normal;

    // Pages
    VerticalLayout {
        y: 0px;
        height: parent.height - self.y;
        width: 100%;
        ConnectionsPage { }
    }

    // Topmost rendered component
    Titlebar { }
}
