import { Theme } from "../themes/theme.slint";
import { Layout } from "../themes/layout.slint";
import { Button } from "../components/Button.slint";
import { GridComponent } from "../components/GridComponent.slint";
import { HorizontalBox, VerticalBox } from "std-widgets.slint";
import {
    ApplicationSplash,
} from "../components/connections_page/ApplicationSplash.slint";
import {
    NewConnectionForm,
} from "../components/connections_page/NewConnectionForm.slint";
import {
    ConnectionsList,
} from "../components/connections_page/ConnectionsList.slint";
import {
    ConnectionsFooter,
} from "../components/connections_page/ConnectionsFooter.slint";
import { ApplicationState } from "../application_state.slint";

export global ConnectionsPageEvents { }

export component ConnectionsPage {

    // Properties
    width: 100%;
    height: 100%;
    horizontal-stretch: 1;
    vertical-stretch: 1;

    // Background Decoration
   GridComponent {
        width: ApplicationState.window-width >= 1100px ? 50% : 100%;
        x: 0;
    }

    Rectangle {
        x: ApplicationState.window-width >= 1100px ? -500px : -200px;
        y: (parent.height - self.height) / 2;
        width: 100%;
        height: 100%;
        background: @radial-gradient(circle, rgba(33,200,255,0.07) 0%, transparent 50%);
    }

    Rectangle {
        y: 0;
        x: 0;
        width: 100%;
        height: 100%;
        background: @linear-gradient(180deg, transparent 0%, rgba(33,200,255,0.02) 100%);
    }

    HorizontalLayout {
        width: 100%;
        height: 100%;
        horizontal-stretch: 1;
        vertical-stretch: 1;

        // Left side
        if ApplicationState.window-width >= 1100px:
        VerticalLayout {
            horizontal-stretch: 1;
            padding: 60px;
            padding-left: 56px;
            padding-right: 56px;
            spacing: 0px;
            max-width: 900px;

            ApplicationSplash { }

            Rectangle {
                vertical-stretch: 1;
            }

            NewConnectionForm {
                available-vertical-space: ApplicationState.window-height - 500px;
            }
        }

        // Spacer
        Rectangle {
            background: #0f1213;
            width: 1px;
        }

        // Right side
        VerticalLayout {
            horizontal-stretch: 2;
            padding: 15px;
            padding-top: 50px;
            width: ApplicationState.window-width > 1100px ? 50% : 100%;
            ConnectionsList { }

            Rectangle {
                vertical-stretch: 1;
            }

            ConnectionsFooter { }
        }
    }
}
