import { Theme } from "../themes/theme.slint";
import { Layout } from "../themes/layout.slint";
import { Button } from "../components/Button.slint";
import { GridComponent } from "../components/GridComponent.slint";
import { HorizontalBox, VerticalBox } from "std-widgets.slint";
import {
    ApplicationSplash,
} from "../components/connections_page/ApplicationSplash.slint";
import {
    NewConnectionForm,
} from "../components/connections_page/NewConnectionForm.slint";
import {
    ConnectionsList,
} from "../components/connections_page/ConnectionsList.slint";
import {
    ConnectionsFooter,
} from "../components/connections_page/ConnectionsFooter.slint";

export global ConnectionsPageEvents { }

export component ConnectionsPage {

    // Properties
    width: 100%;
    height: 100%;
    horizontal-stretch: 1;
    vertical-stretch: 1;

    // Background Decoration
    GridComponent {
        width: 50%;
        x: 0;
    }

    Rectangle {
        x: -500px;
        y: (parent.height - self.height) / 2;
        width: 100%;
        height: 100%;
        background: @radial-gradient(circle, rgba(33,200,255,0.07) 0%, transparent 50%);
    }

    Rectangle {
        y: 0;
        x: 0;
        width: 100%;
        height: 100%;
        background: @linear-gradient(180deg, transparent 0%, rgba(33,200,255,0.02) 100%);
    }

    HorizontalLayout {
        width: 100%;
        height: 100%;
        horizontal-stretch: 1;
        vertical-stretch: 1;
        VerticalLayout {
            padding: 60px;
            padding-left: 56px;
            padding-right: 56px;
            spacing: 0px;

            ApplicationSplash { }

            Rectangle {
                vertical-stretch: 1;
            }

            NewConnectionForm { }
        }

        Rectangle {
            background: hsv(160, 50%, 2%);
            width: 1px;
        }

        VerticalLayout {
            padding: 10px;
            ConnectionsList { }

            Rectangle {
                vertical-stretch: 1;
            }

            ConnectionsFooter { }
        }
    }
}
