import { Theme } from "../themes/theme.slint";
import { Layout } from "../themes/layout.slint";
import { Button } from "../components/Button.slint";
import { GridComponent } from "../components/GridComponent.slint";
import { HorizontalBox, VerticalBox } from "std-widgets.slint";
import {
    ApplicationSplash,
} from "../components/connections_page/ApplicationSplash.slint";
import {
    NewConnectionForm,
} from "../components/connections_page/NewConnectionForm.slint";

export global ConnectionsPageEvents {
    callback button-clicked;
}

export component ConnectionsPage {

    // Properties
    width: 100%;
    height: 100%;
    GridComponent { }
    // Gradient overlay (equivalent to ::before)
    Rectangle {
        width: 100%;
        height: 100%;
        background: @linear-gradient(180deg, transparent 0%, #4da6ff05 100%);
    }

    HorizontalLayout {
        VerticalLayout {
            padding: 60px;
            padding-left: 56px;
            padding-right: 56px;
            spacing: 0px;

            ApplicationSplash { }

            // Spacer equivalent to "my-auto"
            Rectangle {
                vertical-stretch: 1;
            }

            NewConnectionForm { }
        }
    }
}
