import { Theme } from "../themes/theme.slint";
export component GridComponent {
    in property <color> line-color: hsv(160, 50%, 2%);
    in property <length> cell-size: 56px;
    property <int> cols: root.width / root.cell-size + 1;
    property <int> rows: root.height / root.cell-size + 1;
    height: 100%;
    width: 100%;

    // Vertical lines
    for i in root.cols: Rectangle {
        x: i * root.cell-size;
        y: 0;
        width: 1px;
        height: root.height;
        background: root.line-color;
    }

    // Horizontal lines
    for i in root.rows: Rectangle {
        x: 0;
        y: i * root.cell-size;
        width: root.width;
        height: 1px;
        background: root.line-color;
    }
}
