import { Layout } from "../../themes/layout.slint";
import { Button, Color } from "../Button.slint";
import { Input } from "../Input.slint";
import { Icons } from "../../icons.slint";
export component ConnectionsList {
    VerticalLayout {
        spacing: 10px;
        HorizontalLayout {
            spacing: 10px;
            Text {
                text: "Saved conections";
                font-size: Layout.text.xxxl;
            }

            Rectangle {
                horizontal-stretch: 1;
            }

            Button {
                text: "Import";
                start-icon: Icons.upload;
            }

            Button {
                text: "New Connection";
                start-icon: Icons.plus;
                color: Color.primary;
            }
        }

        Input {
            placeholder: "Search for connections, host, paths...";
            start-icon: Icons.magnify;
            end-icon: Icons.upload;
        }
    }
}
