import { Layout } from "../../themes/layout.slint";
import { Theme } from "../../themes/theme.slint";
import { Icons } from "../../icons.slint";

export struct Tag {
    name: string,
    code: string,
    color: color,
    selected-color: color,
    dark-color: color,
}


export global Tags {
    out property <Tag> production: {name: "production", code: "prod", color: #d74745, selected-color: #9e2625, dark-color: #290b0a};
    out property <Tag> staging: {name: "staging", code: "stag", color: #d29000, selected-color: #805a00, dark-color: #221300};
    out property <Tag> development: {name: "development", code: "dev", color: #04ab62, selected-color: #027a46, dark-color: #001c0b};
    out property <Tag> other: {name: "other", code: "other", color: #907ae9, selected-color: #6250a3, dark-color: #1c172c};
}

export enum ConnectionType{
    SFTP,
    FTP,
    S3,
    Other
}

export component ConnectionItem {
    in property <string> connection-name;
    in property <string> user;
    in property <string> host;
    in property <int> port;
    in property <string> path;
    in property <Tag> tag;
    in property <ConnectionType> connection-type;

    property <brush> background: connection-type == ConnectionType.SFTP ? @linear-gradient(-45deg, #001828 0%, #003858 100%) : connection-type == ConnectionType.S3 ? @linear-gradient(-45deg, #280606 0%, #610000 100%) : @linear-gradient(-45deg, #260a00 0%, #540f00 100%);
    property <brush> border: connection-type == ConnectionType.SFTP ? @linear-gradient(0deg, #0f3a55 0%, #0f3a55 100%) : connection-type == ConnectionType.S3 ? @linear-gradient(0deg, #5d0f10 0%, #5d0f10 100%) : @linear-gradient(0deg, #4e1c0f 0%, #4e1c0f 100%);
    property <brush> color: connection-type == ConnectionType.SFTP ? #46dcfd : connection-type == ConnectionType.S3 ? #fda299 : #d08754;
    property <string> character: connection-type == ConnectionType.SFTP ? "S" : connection-type == ConnectionType.FTP ? "F" : connection-type == ConnectionType.S3 ? "S3" : "U";

    HorizontalLayout {
        spacing: 8px;
        Rectangle {
            background: background;
            width: 32px;
            height: 32px;
            border-radius: Layout.radius.lg;
            border-color: border;
            border-width: 1px;
            Text {
                text: character;
                color: color;
                font-family: Layout.font.mono;
            }
        }

        VerticalLayout {
            Text {
                text: connection-name;
                font-weight: Layout.weight.bold;
                font-size: Layout.text.lg;
            }

            Text {
                text: "\{user}@\{host}:\{port} - \{path}";
                font-family: Layout.font.mono;
                font-size: Layout.text.sm;
                color: Theme.palette.ink.ink03;
            }
        }

        Rectangle {
            horizontal-stretch: 1;
        }

        Rectangle {
            width: 48px;
            height: 24px;
            background: tag.dark-color;
            border-color: tag.color;
            border-width: 1px;
            border-radius: Layout.radius.sm;
            Text {
                text: tag.code.to-uppercase();
                font-size: Layout.text.sm;
                font-family: Layout.font.mono;
                color: tag.color;
            }
        }

        Image {
            source: Icons.chevron;
            colorize: Theme.palette.ink.ink04;
            width: 16px;
            height: 16px;
            transform-rotation: -90deg;
            y: 5px;
        }
    }
}
