import { Theme } from "../../themes/theme.slint";

export component FloatingLogo {
    width: 100px;
    height: 100px;
    property <length> offset: 5px;
    property <duration> duration: 2s;

    property <bool> is-bounce-y: false;
    property <length> bounce-y: is-bounce-y ? -offset : offset;

    animate bounce-y {
        duration: duration;
        iteration-count: -1;       // loop forever
        direction: alternate;      // plays forward then backward = smooth bounce
        easing: ease-in-out;
    }

    Timer {
        interval: duration;
        triggered => {
            is-bounce-y = !is-bounce-y
        }
        running: true;
    }

    Rectangle {
        y: root.bounce-y;
        background: @radial-gradient(circle, Theme.palette.accent.glow 20%, transparent 75%);
        width: root.width;
        height: root.height;
    }

    Image {
        y: root.bounce-y;
        source: @image-url("../../../../../res/icons/icon.png");
        width: root.width - 5px;
        height: root.height - 5px;
    }
}
